### ISSUE TITLE
Difference?

### ISSUE THREAD

**Issue by thesbros** [linuxmasterrace/website-foundation#6]
What's the difference between website and website-foundation?

**Comment by nixi-awoo** [comment]
website-foundation uses the Zurb Foundation 5 framework, whereas webpage repository is used for a page build withou a framework, since some people wanted to work on that instead.

**Comment by thesbros** [comment]
Okay, thanks

**Comment by nixi-awoo** [comment]
Although, if we are ditching the no-framework page, we should rename 'webpage-foundation' to 'webpage'

**Comment by thesbros** [comment]
I'm going to work on it a bit tomorrow and see how it goes
